# Generated by Django 3.2.4 on 2021-06-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='id_user', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=50)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
